src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as VICH;
use function dump;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @VICH\Uploadable
 */
class Property
{
    
    const HEAT = [
        0 => 'électrique',
        1 => 'gaz'
    ];
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $fileName;


    /**
     * @var File|null
     * @Assert\Image(mimeTypes="image/jpeg")
     * @VICH\UploadableField(mapping="property_image", fileNameProperty="fileName")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\ManyToMany(targetEntity="Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;
    
    function __construct() {
        $this->create_at = new DateTime();
        $this->options = new ArrayCollection();
    }

        public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string {
        
        return (new Slugify())->slugify($this->title);
        
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreateAt(): ?DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    
    public function getHeatType(): string {
        
        return self::HEAT[$this->heat];
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    /**
     * 
     * @param Option $option
     * @return self
     */
    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    /**
     * 
     * @param Option $option
     * @return self
     */
    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }
    
    /**
     * 
     * @return string|null
     */
    function getFileName(): ?string {
        return $this->fileName;
    }

    /**
     * 
     * @return File|null
     */
    function getImageFile(): ?File {
        return $this->imageFile;
    }

    /**
     * 
     * @param string|null $fileName
     * @return self
     */
    function setFileName(?string $fileName): self {
        if ($fileName){
            $this->fileName = $fileName;
        }
        dump($fileName);
        return $this;
    }

    /**
     * 
     * @param File|null|UploadedFile $imageFile
     * @return self
     */
    function setImageFile(?File $imageFile): self {
        $this->imageFile = $imageFile;
        dump($imageFile);
        if (null !== $imageFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
                ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
                ])
            ->add('imageFile', FileType::class, [
                'required' => false                
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'form'
        ]);
    }
    
    public function getChoices(): array {
        return array_flip(Property::HEAT);
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
//use App\Notification\ContactNotificationMailer;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
 * Description of PropertyController
 *
 * @author didier
 */
class PropertyController extends AbstractController {

    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @var PropertyRepository
     */
    private $repository;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em) {
        
        $this->repository = $repository;
        $this->em = $em;
    }

    
    /**
     * @Route("/biens", name="property.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response{
        
        // Créer une entité qui va représenter notre recherche
        //     prix maximum, nombre de pièces
        // Créer un formulaire
        // gérer le traitement dans le controller (handleRequest ...)
        // passer l'entité qui représente la recherche à la méthode findAllVisibleQuery($searchData)
        
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        
        $properties = $paginator->paginate(
                $this->repository->findAllVisibleQuery($search),
                $request->query->getInt('page', 1),
                9);
        
        return $this->render('property/index.html.twig',
                ['current_menu' => 'properties',
                 'properties' => $properties,
                 'form' => $form->createView()
                ]);
    }
    
    /**
     * @Route("/biens/{slug}.{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */
    //public function show(Property $property, string $slug, Request $request, ContactNotificationMailer $notification): Response {
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response {
    //public function show($slug, $id): Response {    
    //    $property = $this->repository->find($id);
        if ($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show',
                    [
                        'id' => $property->getId(),
                        'slug' => $property->getSlug()
                    ], 301);    // rediection permanente
        }
        // ajouter partie 11
        $contact = new Contact;
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()){
            $notification->notify($contact);
            $this->addFlash('success', 'Votre demande à bien été envoyée');
//            return $this->redirectToRoute('property.show',
//                    [
//                        'id' => $property->getId(),
//                        'slug' => $property->getSlug()
//                    ]);
            }
        
        return $this->render('property/show.html.twig',
           ['property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()      // ajouté en partie 11
           ]); 
 
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.filename %}
        <!--img src="/images/properties/{{ property.filename }}" alt="card-img-top" style="width: 100%; height: auto;"-->
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% else %}
        <img src={{ '/images/properties/empty.jpg' | imagine_filter('thumb') }} alt="card-img-top" style="width: 100%; height: auto;">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                {{ property.title }}
            </a>
        </h5>
        <p class="card-text">
            {{ property.city }} ({{ property.postalCode }})
        </p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold;">
            {{ property.formatedPrice }} €
        </div>
    </div>
</div>

templates/property/index.html.twig
{%  extends "base.html.twig" %}

{% block title 'Tous nos biens' %}

    {% block body %}
        
        <div class="jumbotron">
            <div class="container">
                {{ form_start(form) }}
                    <div class="form-row">
                        <div class="col">{{  form_row(form.minSurface) }}</div>
                        <div class="col">{{  form_row(form.maxPrice) }}</div>
                        <div class="col">{{  form_row(form.options) }}</div>
                        <div class="col"><button class="btn btn-primary">Rechercher</button></div>
                    </div>
                {{ form_end(form) }}
            </div>
        </div>

        <div class="container mt-4">
            <h1>Voir tous nos biens</h1>

            <div class="row">

                {% for property in properties %}
                    <div class="col-md-4">
                        {% include 'property/_property.html.twig' %}
                    </div>
                {% endfor %}

            </div>

            <div class="pagination">
                {{ knp_pagination_render(properties) }}
            </div>
        </div>

    {% endblock %}

templates/property/show.html.twig
{%  extends "base.html.twig" %}

{% block title property.title %}

    {% block body %}

        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                    {% if property.filename %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto;">
                    {% else %}
                        <img src={{ '/images/properties/empty.jpg' | imagine_filter('medium') }} alt="card-img-top" style="width: 100%; height: auto;">
                    {% endif %}
                    </div>
                    <div class="col-md-4">
                        <h1>{{ property.title }}</h1>
                        <h2>{{ property.rooms }} pièces . {{ property.surface }} m2</h2>
                        <div class="text-primary" style="font-weight: bold; font-size: 4rem">{{ property.formatedPrice }} €</div>
                        <a href="#" class="btn btn-primary">Contacter l'agence</a>
                        <div id="contactForm" class="mt-4">
                            {{ form_start(form) }}
                            <div class="row">
                                <div class="col">{{ form_row(form.firstname) }}</div>
                                <div class="col">{{ form_row(form.lastname) }}</div>
                            </div>
                            <div class="row">
                                <div class="col">{{ form_row(form.phone) }}</div>
                                <div class="col">{{ form_row(form.email) }}</div>
                            </div>
                            {{ form_rest(form) }}
                            <div class="form-group">
                                <button class="btn btn-primary">Envoyer</button>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
                        
        <div class="container mt-4">
            <p>
                {{ property.description | nl2br }}
            </p>

            <div class="row">
                <div class="col-md-8">
                    <h2>Caractéristiques</h2>
                    <table class="table table-striped">
                        <tr>
                            <td>Surface habitable</td>
                            <td>{{ property.surface }} m2</td>
                        </tr>
                        <tr>
                            <td>Pièces</td>
                            <td>{{ property.rooms }} m2</td>
                        </tr>
                        <tr>
                            <td>Surface habitable</td>
                            <td>{{ property.surface }} m2</td>
                        </tr>
                        <tr>
                            <td>Chambres</td>
                            <td>{{ property.bedRooms }} m2</td>
                        </tr>
                        <tr>
                            <td>Etage</td>
                            <td>{{ property.floor }} m2</td>
                        </tr>
                        <tr>
                            <td>Chauffage</td>
                            <td>{{ property.heatType }} m2</td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-4">
                    <h2>Spécificités</h2>
                    <ul class="list-group">
                        {% for option in property.options %}
                            <li class="list-group-item">{{ option.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        {% endblock %}